#!/usr/bin/ruby

def do_cygstart(shargs)
  system("cygstart", *shargs)
end

ARGV.each_with_index do |arg, i|
  case arg
    when "--" then
      # immediately run do_cygstart with everything past '--'
      shargs = ARGV[i + 1, ARGV.length]
      do_cygstart(shargs)
      exit
    else
      do_cygstart([arg])
  end
end
