#!/usr/bin/ruby

require 'Win32API'

GetShortPathName = Win32API.new('kernel32', 'GetShortPathName', ['P', 'P', 'I'], 'I')
GetLastError = Win32API.new('kernel32', 'GetLastError', [], 'I')

ARGV.each do |arg|
  path = arg
  len = GetShortPathName.call(path.dup, nil, 0)
  if len.zero? then
    err = GetLastError.call()
    if err == 3 then # file not found
      raise IOError, "file #{path.inspect} not found"
    else
      puts path
    end
  else
    buffer = ("\0" * len)
    GetShortPathName.call(path.dup, buffer, len)
    puts buffer
  end
end
