#!/usr/bin/ruby

def stringify(array, joinval=",")
  na = array.map do |val|
    next val.inspect
  end
  return na.join(joinval)
end

if ARGV.length then
  exopts = []
  argv = []
  ARGV.each do |arg|
    if arg[0] == '-' then
      exopts << arg
    else
      argv << arg
    end
  end
  argv.each do |url|
    cmd = ["curl", "-J", "-O", "-L", *exopts, url]
    puts("** system(#{stringify(cmd)})")
    system(*cmd)
  end
else
  puts "Usage: cget <urls...>"
end

